### ISSUE TITLE
timestamp in odometry.csv

### ISSUE THREAD

**Issue by Eunju-Jeong178** [kekeblom/StrayVisualizer#14]
Hello. Thank you for sharing.

I wonder what the timestamp of odometry.csv means.

I thought this was a unix timestamp, so I converted it to human date time, and although it was a timestamp obtained by the Stray scanner app on July 27, 2022, the time zone came out on January 1, 1970.

How do I get the current unix timestamp or date time in real-time through the Stray scanner app?

**Comment by kekeblom** [comment]
The timestamp is starting from when the phone was last booted. For some reason this is the timestamp given by ARKit for the frames.

What is your use case where you would need these to match human date and time? It could make sense to either write down the start date and time in some metadata or write the unix timestamp in the csv files, but haven't really had a use case for it yet.

**Comment by Eunju-Jeong178** [comment]
Thank you for your reply.

I am going to collect odometry, RGB, and depth images with the Stray scanner and measure the distance with a LiDAR sensor at the same time. To synchronize the time between the Stray scanner and the LiDAR sensor, I need to know the unix timestamp of the data collected by the Stray scanner.

**Comment by kekeblom** [comment]
That's an interesting use case. My first thought would be that this would require quite a bit more fine grained synchronization than simply using timestamps from the device clock. Might be easier to just localize both datasets against the same map.  

Maybe synchronizing through the 3.5mm heaphone jack or something could work, but definitely not within the scope of this app.

I've thought about open sourcing the app so people could hack it for all kinds of weird projects. 

What kind of LiDAR sensor did you have in mind? Some commercial ready made LiDAR scanner or is it a self-made one?

**Comment by Eunju-Jeong178** [comment]
I will use LiDAR Lite v3, a commercially ready-made LiDAR. I will use four LiDAR Lite v3s with a Stray scanner.
https://www.garmin.com/en-US/p/557294
