### ISSUE TITLE
Resolution of iphone 12 pro's lidar

### ISSUE THREAD

**Issue by chenzhao2018** [kekeblom/StrayVisualizer#2]
Hi, I have recently used Stray Scanner. I found the resolution of depth image is 256*192. Is it right?
  I want to know the real resolution of iphone 12 pro's lidar, but I can't find the parameter through search engines and Apple offical documents. Can you tell me?
  Look forward to your apply.

**Comment by kekeblom** [comment]
Hey @chenzhao2018,

Great to hear that you already got some use out of the app.

The resolution of the depth map that is exposed by ARKit is 256 * 192 as you suggest. This corresponds to the `.sceneDepth` property of of the `ARFrame` object.

Happy to answer any further questions.

**Comment by chenzhao2018** [comment]
Thank you so much. And I have a further question.

How to get data of depth image and color image after depth image registration in Swift code?
