### ISSUE TITLE
AttributeError: 'FFmpegWriter' object has no attribute '_proc'

### ISSUE THREAD

**Issue by KIMSUEUN73** [kekeblom/StrayVisualizer#5]
Hi,

there was a problem when I tried to create a video from the depth maps

as I am not using iphone 12 yet, I downloaded the example datasets which you uploaded (ZB1, ZB2, ZB3)

and when I tried to run the code 
"python make_video.py <dataset-path>",
I ran into the error : 

Traceback (most recent call last):
  File "make_video.py", line 39, in <module>
    main()
  File "make_video.py", line 36, in main
    writer.close()
  File "/opt/anaconda3/envs/stray_scanner/lib/python3.7/site-packages/skvideo/io/abstract.py", line 474, in close
    if self._proc is None:  # pragma: no cover
AttributeError: 'FFmpegWriter' object has no attribute '_proc'

I have no idea what to do. 
I checked the version of scikit-video and tried it to be re-installed, but didn't work.

**Comment by kekeblom** [comment]
This seems like a ffmpeg issue. What happens if you run `ffmpeg --version` in your shell? Maybe ffmpeg is not installed and installing scikit-video does not install it. 

If the ffmpeg command results in a command not found error, I would proceed by instaling ffmpeg.
