### ISSUE TITLE
Get the depth value in meters

### ISSUE THREAD

**Issue by kushalp28** [kekeblom/StrayVisualizer#6]
Hi, I wanted to know how to get the depth value in meters in python of the recorded video?

**Comment by kekeblom** [comment]
Check the function `load_depth(path, confidence=None, filter_level=0)` in `stray_visualize.py`. The depth values are saved as millimeters encoded as a matrix of 16 bit unsigned integer values. To go from millimeters to meters you multiply by 1000.
