### ISSUE TITLE
How to calculate odometry from Stray Scanner?

### ISSUE THREAD

**Issue by anhpham96** [kekeblom/StrayVisualizer#9]
Hi, I have used Stray Scanner app and I'm really curious about the odometry information. 
I have tried to develop a small app to get quaternion (simd_quatf(frame.camera.transform)) and the position to get the extrinsic camera.
But when I input the dataset from my app to Stray Visualizer, it's not show okay. 
Do I have to scale or apply anything to odometry? If I need to scale, What ratio I should to scale by? 
Could your share me how to calculate the odometry each frames.
Thank you, hope you reply.

**Comment by kekeblom** [comment]
Not sure what kind of data you are dealing at. Was it collected using the Stray Scanner app? That should work correctly out of the box.

In case you are interested in getting the trajectory of the camera with a scene reconstruction, I might recommend you look at the  Stray Robots Toolkit https://docs.strayrobots.io/. This will even work with data coming from other devices.
